//------------------------------------------------------------------------
// Copyright(c) 2024 Tiki Audio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"MIDI-to-DMX-Controller.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MIDI-to-DMX-Controller VST3 (64Bit)"
#else
#define stringFileDescription	"MIDI-to-DMX-Controller VST3"
#endif
#define stringCompanyName		"Tiki Audio\0"
#define stringLegalCopyright	"Copyright(c) 2024 Tiki Audio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
